// Generated by gencpp from file smartcar_msgs/ACCTarget.msg
// DO NOT EDIT!


#ifndef SMARTCAR_MSGS_MESSAGE_ACCTARGET_H
#define SMARTCAR_MSGS_MESSAGE_ACCTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace smartcar_msgs
{
template <class ContainerAllocator>
struct ACCTarget_
{
  typedef ACCTarget_<ContainerAllocator> Type;

  ACCTarget_()
    : header()
    , object_id()
    , relative_dis(0.0)
    , velocity(0.0)  {
    }
  ACCTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_id(_alloc)
    , relative_dis(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_id_type;
  _object_id_type object_id;

   typedef double _relative_dis_type;
  _relative_dis_type relative_dis;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::smartcar_msgs::ACCTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_msgs::ACCTarget_<ContainerAllocator> const> ConstPtr;

}; // struct ACCTarget_

typedef ::smartcar_msgs::ACCTarget_<std::allocator<void> > ACCTarget;

typedef boost::shared_ptr< ::smartcar_msgs::ACCTarget > ACCTargetPtr;
typedef boost::shared_ptr< ::smartcar_msgs::ACCTarget const> ACCTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_msgs::ACCTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_msgs::ACCTarget_<ContainerAllocator1> & lhs, const ::smartcar_msgs::ACCTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_id == rhs.object_id &&
    lhs.relative_dis == rhs.relative_dis &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_msgs::ACCTarget_<ContainerAllocator1> & lhs, const ::smartcar_msgs::ACCTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_msgs::ACCTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_msgs::ACCTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_msgs::ACCTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dc034c3e1b7e7f2a509e71e6d2e2ec0";
  }

  static const char* value(const ::smartcar_msgs::ACCTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dc034c3e1b7e7f2ULL;
  static const uint64_t static_value2 = 0xa509e71e6d2e2ec0ULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_msgs/ACCTarget";
  }

  static const char* value(const ::smartcar_msgs::ACCTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string  object_id  \n"
"float64 relative_dis\n"
"float64 velocity # m/s\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::smartcar_msgs::ACCTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_id);
      stream.next(m.relative_dis);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ACCTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_msgs::ACCTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_msgs::ACCTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_id);
    s << indent << "relative_dis: ";
    Printer<double>::stream(s, indent + "  ", v.relative_dis);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_MSGS_MESSAGE_ACCTARGET_H
