// Generated by gencpp from file smartcar_msgs/VehicleLightState.msg
// DO NOT EDIT!


#ifndef SMARTCAR_MSGS_MESSAGE_VEHICLELIGHTSTATE_H
#define SMARTCAR_MSGS_MESSAGE_VEHICLELIGHTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace smartcar_msgs
{
template <class ContainerAllocator>
struct VehicleLightState_
{
  typedef VehicleLightState_<ContainerAllocator> Type;

  VehicleLightState_()
    : header()
    , turn_light(0)
    , car_light(0)  {
    }
  VehicleLightState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , turn_light(0)
    , car_light(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _turn_light_type;
  _turn_light_type turn_light;

   typedef int32_t _car_light_type;
  _car_light_type car_light;





  typedef boost::shared_ptr< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleLightState_

typedef ::smartcar_msgs::VehicleLightState_<std::allocator<void> > VehicleLightState;

typedef boost::shared_ptr< ::smartcar_msgs::VehicleLightState > VehicleLightStatePtr;
typedef boost::shared_ptr< ::smartcar_msgs::VehicleLightState const> VehicleLightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_msgs::VehicleLightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_msgs::VehicleLightState_<ContainerAllocator1> & lhs, const ::smartcar_msgs::VehicleLightState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.turn_light == rhs.turn_light &&
    lhs.car_light == rhs.car_light;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_msgs::VehicleLightState_<ContainerAllocator1> & lhs, const ::smartcar_msgs::VehicleLightState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e22a6beadc4b37e8e1c81c5e770f4eb";
  }

  static const char* value(const ::smartcar_msgs::VehicleLightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e22a6beadc4b37eULL;
  static const uint64_t static_value2 = 0x8e1c81c5e770f4ebULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_msgs/VehicleLightState";
  }

  static const char* value(const ::smartcar_msgs::VehicleLightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"#0 mid, 1 turn left, 2 turn right\n"
"int32 turn_light \n"
"\n"
"#0 close, 1 small light, 2 dipped headlight, 3 headlights on full beam\n"
"int32 car_light\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::smartcar_msgs::VehicleLightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.turn_light);
      stream.next(m.car_light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleLightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_msgs::VehicleLightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_msgs::VehicleLightState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "turn_light: ";
    Printer<int32_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "car_light: ";
    Printer<int32_t>::stream(s, indent + "  ", v.car_light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_MSGS_MESSAGE_VEHICLELIGHTSTATE_H
