# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smartcar_msgs/VehicleInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import smartcar_msgs.msg
import std_msgs.msg

class VehicleInfo(genpy.Message):
  _md5sum = "ce1548f612651099d85d928f1bef6a2e"
  _type = "smartcar_msgs/VehicleInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Point localization
LongitudinalData longitudinal_data
LateralData lateral_data


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: smartcar_msgs/LongitudinalData
float64 vel_from_localization
float64 vel_from_wheels
float64 acceleration
float64 traveled_distance
float64 fl_wheel_angular_velocity
float64 fr_wheel_angular_velocity
float64 bl_wheel_angular_velocity
float64 br_wheel_angular_velocity
float64 gas_percent
float64 fl_gas_torque
float64 fr_gas_torque
float64 bl_gas_torque
float64 br_gas_torque
float64 fl_brake_Torque
float64 fr_brake_torque
float64 bl_brake_torque
float64 br_brake_torque

================================================================================
MSG: smartcar_msgs/LateralData
float64 heading_angle
float64 steering_wheel_angle_actual
float64 steering_wheel_expected
float64 steering_wheel_error
float64 steering_wheel_cmd

float64 fl_steering_angle_actual
float64 fr_steering_angle_actual
float64 single_track_steering_angle
float64 fl_steering_angle_expected
float64 fr_steering_angle_expected
float64 fl_steering_error
float64 fr_steering_error
float64 fl_steering_cmd
float64 fr_steering_cmd

"""
  __slots__ = ['header','localization','longitudinal_data','lateral_data']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','smartcar_msgs/LongitudinalData','smartcar_msgs/LateralData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,localization,longitudinal_data,lateral_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.localization is None:
        self.localization = geometry_msgs.msg.Point()
      if self.longitudinal_data is None:
        self.longitudinal_data = smartcar_msgs.msg.LongitudinalData()
      if self.lateral_data is None:
        self.lateral_data = smartcar_msgs.msg.LateralData()
    else:
      self.header = std_msgs.msg.Header()
      self.localization = geometry_msgs.msg.Point()
      self.longitudinal_data = smartcar_msgs.msg.LongitudinalData()
      self.lateral_data = smartcar_msgs.msg.LateralData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_34d().pack(_x.localization.x, _x.localization.y, _x.localization.z, _x.longitudinal_data.vel_from_localization, _x.longitudinal_data.vel_from_wheels, _x.longitudinal_data.acceleration, _x.longitudinal_data.traveled_distance, _x.longitudinal_data.fl_wheel_angular_velocity, _x.longitudinal_data.fr_wheel_angular_velocity, _x.longitudinal_data.bl_wheel_angular_velocity, _x.longitudinal_data.br_wheel_angular_velocity, _x.longitudinal_data.gas_percent, _x.longitudinal_data.fl_gas_torque, _x.longitudinal_data.fr_gas_torque, _x.longitudinal_data.bl_gas_torque, _x.longitudinal_data.br_gas_torque, _x.longitudinal_data.fl_brake_Torque, _x.longitudinal_data.fr_brake_torque, _x.longitudinal_data.bl_brake_torque, _x.longitudinal_data.br_brake_torque, _x.lateral_data.heading_angle, _x.lateral_data.steering_wheel_angle_actual, _x.lateral_data.steering_wheel_expected, _x.lateral_data.steering_wheel_error, _x.lateral_data.steering_wheel_cmd, _x.lateral_data.fl_steering_angle_actual, _x.lateral_data.fr_steering_angle_actual, _x.lateral_data.single_track_steering_angle, _x.lateral_data.fl_steering_angle_expected, _x.lateral_data.fr_steering_angle_expected, _x.lateral_data.fl_steering_error, _x.lateral_data.fr_steering_error, _x.lateral_data.fl_steering_cmd, _x.lateral_data.fr_steering_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.localization is None:
        self.localization = geometry_msgs.msg.Point()
      if self.longitudinal_data is None:
        self.longitudinal_data = smartcar_msgs.msg.LongitudinalData()
      if self.lateral_data is None:
        self.lateral_data = smartcar_msgs.msg.LateralData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 272
      (_x.localization.x, _x.localization.y, _x.localization.z, _x.longitudinal_data.vel_from_localization, _x.longitudinal_data.vel_from_wheels, _x.longitudinal_data.acceleration, _x.longitudinal_data.traveled_distance, _x.longitudinal_data.fl_wheel_angular_velocity, _x.longitudinal_data.fr_wheel_angular_velocity, _x.longitudinal_data.bl_wheel_angular_velocity, _x.longitudinal_data.br_wheel_angular_velocity, _x.longitudinal_data.gas_percent, _x.longitudinal_data.fl_gas_torque, _x.longitudinal_data.fr_gas_torque, _x.longitudinal_data.bl_gas_torque, _x.longitudinal_data.br_gas_torque, _x.longitudinal_data.fl_brake_Torque, _x.longitudinal_data.fr_brake_torque, _x.longitudinal_data.bl_brake_torque, _x.longitudinal_data.br_brake_torque, _x.lateral_data.heading_angle, _x.lateral_data.steering_wheel_angle_actual, _x.lateral_data.steering_wheel_expected, _x.lateral_data.steering_wheel_error, _x.lateral_data.steering_wheel_cmd, _x.lateral_data.fl_steering_angle_actual, _x.lateral_data.fr_steering_angle_actual, _x.lateral_data.single_track_steering_angle, _x.lateral_data.fl_steering_angle_expected, _x.lateral_data.fr_steering_angle_expected, _x.lateral_data.fl_steering_error, _x.lateral_data.fr_steering_error, _x.lateral_data.fl_steering_cmd, _x.lateral_data.fr_steering_cmd,) = _get_struct_34d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_34d().pack(_x.localization.x, _x.localization.y, _x.localization.z, _x.longitudinal_data.vel_from_localization, _x.longitudinal_data.vel_from_wheels, _x.longitudinal_data.acceleration, _x.longitudinal_data.traveled_distance, _x.longitudinal_data.fl_wheel_angular_velocity, _x.longitudinal_data.fr_wheel_angular_velocity, _x.longitudinal_data.bl_wheel_angular_velocity, _x.longitudinal_data.br_wheel_angular_velocity, _x.longitudinal_data.gas_percent, _x.longitudinal_data.fl_gas_torque, _x.longitudinal_data.fr_gas_torque, _x.longitudinal_data.bl_gas_torque, _x.longitudinal_data.br_gas_torque, _x.longitudinal_data.fl_brake_Torque, _x.longitudinal_data.fr_brake_torque, _x.longitudinal_data.bl_brake_torque, _x.longitudinal_data.br_brake_torque, _x.lateral_data.heading_angle, _x.lateral_data.steering_wheel_angle_actual, _x.lateral_data.steering_wheel_expected, _x.lateral_data.steering_wheel_error, _x.lateral_data.steering_wheel_cmd, _x.lateral_data.fl_steering_angle_actual, _x.lateral_data.fr_steering_angle_actual, _x.lateral_data.single_track_steering_angle, _x.lateral_data.fl_steering_angle_expected, _x.lateral_data.fr_steering_angle_expected, _x.lateral_data.fl_steering_error, _x.lateral_data.fr_steering_error, _x.lateral_data.fl_steering_cmd, _x.lateral_data.fr_steering_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.localization is None:
        self.localization = geometry_msgs.msg.Point()
      if self.longitudinal_data is None:
        self.longitudinal_data = smartcar_msgs.msg.LongitudinalData()
      if self.lateral_data is None:
        self.lateral_data = smartcar_msgs.msg.LateralData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 272
      (_x.localization.x, _x.localization.y, _x.localization.z, _x.longitudinal_data.vel_from_localization, _x.longitudinal_data.vel_from_wheels, _x.longitudinal_data.acceleration, _x.longitudinal_data.traveled_distance, _x.longitudinal_data.fl_wheel_angular_velocity, _x.longitudinal_data.fr_wheel_angular_velocity, _x.longitudinal_data.bl_wheel_angular_velocity, _x.longitudinal_data.br_wheel_angular_velocity, _x.longitudinal_data.gas_percent, _x.longitudinal_data.fl_gas_torque, _x.longitudinal_data.fr_gas_torque, _x.longitudinal_data.bl_gas_torque, _x.longitudinal_data.br_gas_torque, _x.longitudinal_data.fl_brake_Torque, _x.longitudinal_data.fr_brake_torque, _x.longitudinal_data.bl_brake_torque, _x.longitudinal_data.br_brake_torque, _x.lateral_data.heading_angle, _x.lateral_data.steering_wheel_angle_actual, _x.lateral_data.steering_wheel_expected, _x.lateral_data.steering_wheel_error, _x.lateral_data.steering_wheel_cmd, _x.lateral_data.fl_steering_angle_actual, _x.lateral_data.fr_steering_angle_actual, _x.lateral_data.single_track_steering_angle, _x.lateral_data.fl_steering_angle_expected, _x.lateral_data.fr_steering_angle_expected, _x.lateral_data.fl_steering_error, _x.lateral_data.fr_steering_error, _x.lateral_data.fl_steering_cmd, _x.lateral_data.fr_steering_cmd,) = _get_struct_34d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_34d = None
def _get_struct_34d():
    global _struct_34d
    if _struct_34d is None:
        _struct_34d = struct.Struct("<34d")
    return _struct_34d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
