(cl:in-package smartcar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          VALID-VAL
          VALID
          SPACE_FRAME-VAL
          SPACE_FRAME
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          HEADING-VAL
          HEADING
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          SPEED-VAL
          SPEED
          FOOT_LF-VAL
          FOOT_LF
          FOOT_LR-VAL
          FOOT_LR
          FOOT_RF-VAL
          FOOT_RF
          FOOT_RR-VAL
          FOOT_RR
          UTM_X-VAL
          UTM_X
          UTM_Y-VAL
          UTM_Y
          UTM_Z-VAL
          UTM_Z
          UTM_HEADING-VAL
          UTM_HEADING
          UTM_FOOT_LF-VAL
          UTM_FOOT_LF
          UTM_FOOT_LR-VAL
          UTM_FOOT_LR
          UTM_FOOT_RF-VAL
          UTM_FOOT_RF
          UTM_FOOT_RR-VAL
          UTM_FOOT_RR
          UTM_TWIST-VAL
          UTM_TWIST
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
          INDICATOR_STATE-VAL
          INDICATOR_STATE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          USER_DEFINED_INFO-VAL
          USER_DEFINED_INFO
          IS_STATIC-VAL
          IS_STATIC
          TRAJECTORY_-VAL
          TRAJECTORY_
))