(cl:in-package smartcar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INS_TIME-VAL
          INS_TIME
          GLOBAL_POS-VAL
          GLOBAL_POS
          WGS84_POS-VAL
          WGS84_POS
          GLOBAL_SPEED-VAL
          GLOBAL_SPEED
          ACCELERATE-VAL
          ACCELERATE
          ORIENTATION-VAL
          ORIENTATION
          RPY_RATE-VAL
          RPY_RATE
          SPEED-VAL
          SPEED
          V_X-VAL
          V_X
          V_Y-VAL
          V_Y
          V_Z-VAL
          V_Z
          ACCEL_X-VAL
          ACCEL_X
          ACCEL_Y-VAL
          ACCEL_Y
          ACCEL_Z-VAL
          ACCEL_Z
          INS_STD_ERROR-VAL
          INS_STD_ERROR
          INS_DATA_INFO-VAL
          INS_DATA_INFO
          INS_STATUS-VAL
          INS_STATUS
))